//json with name, url, description, and optional image
export const storm = [
    { 
        name:'Active Storms',
        path:'active-storms',
        url:'http://sirocco.accuweather.com/sat_mosaic_640x480_public/ei/isaemex.gif',
        desc:'Satellite images of the tropical storm',
        url2:'http://tropic.ssec.wisc.edu/real-time/mimtc/2018_03E/web/last48hrs.gif',
        desc2:'microwave satellite image',
        url3:'',
        desc3:'',
        url4:'',
        desc4:'',
        url5:'',
        desc5:'',
        description:'',
        image:''
    },
    { 
        name:'Conditions in the Atlantic Ocean',
        path:'conditions-atlantic',
        url:'https://cdn.star.nesdis.noaa.gov/GOES16/ABI/GIFS/GOES16-TAW-GEOCOLOR-900x540.gif',
        url2:'https://cdn.star.nesdis.noaa.gov/GOES16/ABI/GIFS/GOES16-CONUS-GEOCOLOR-625x375.gif',
        url3:'http://derecho.math.uwm.edu/models/quicklook-gtwo.png',
        url4:'http://www.nhc.noaa.gov/xgtwo/two_atl_0d0.png',
        url5:'http://www.nhc.noaa.gov/xgtwo/two_atl_2d0.png',
        url6:'http://www.nhc.noaa.gov/xgtwo/two_atl_5d0.png',
        url7:'https://www.nhc.noaa.gov/storm_graphics/AT13/refresh/AL132022_5day_cone_no_line_and_wind+png/114708_5day_cone_no_line_and_wind.png',
        url8:'http://weather.cod.edu/data/satellite/global/atlantic/current/atlantic.14.jpg',
        url9:'https://cdn.star.nesdis.noaa.gov/GOES16/ABI/SECTOR/taw/14/900x540.jpg',
        url10:'http://tropic.ssec.wisc.edu/real-time/atlantic/images/irng8.GIF',
        url11:'http://tropic.ssec.wisc.edu/real-time/atlantic/images/xxirg8bbm.jpg',
        url12:'http://weather.cod.edu/data/satellite/regional/gulf/current/gulf.14.jpg',
        url13:'http://tropic.ssec.wisc.edu/real-time/europe/images/irnm7.GIF',
        desc13: 'Satellite image of the East Atlantic and Africa (infrared image)',
        url14:'http://weather.cod.edu/data/satellite/global/atlantic/current/atlantic.02.jpg',
        desc14: 'Visible satellite image of the Atlantic',
        url15:'http://tropic.ssec.wisc.edu/real-time/atlantic/images/xxwvg8bbm.jpg',
        desc15:'Atlantic water vapor image',
        url16:'http://sirocco.accuweather.com/sat_mosaic_640x480_public/ei/isaehatl.gif',
        desc16:'Atlantic Ocean Satellite Animation',
        url17:'http://tropic.ssec.wisc.edu/real-time/mtpw2/webAnims/tpw_nrl_colors/natl/mimictpw_natl_latest.gif',
        desc17:'Total precipitable water in the Atlantic Ocean',
        url18:'http://www.ssd.noaa.gov/PS/TROP/DATA/RT/SST/ATL/20.jpg',
        desc18:'Sea surface temperature, NOAA analysis (SST/SST)',
        url19:'http://tropic.ssec.wisc.edu/real-time/sal/g16split/g16split.jpg',
        desc19:'Saharan dust in the Atlantic Ocean, CIMSS analysis',
        url20:'http://tropic.ssec.wisc.edu/real-time/sal/splitE.jpg',
        desc20:'Saharan dust in the Atlantic Ocean, CIMSS analysis',
        url21:'http://www.ssd.noaa.gov/PS/TROP/TCFP/data/current/al_rCUMP_048.gif',
        desc21:'Probability of cyclone formation during the next 48 hours (current conditions)',
        url22:'http://www.nhc.noaa.gov/tafb_latest/danger_atl_latestBW.gif',
        desc22:'Probability of cyclone formation during the next 48 hours (current conditions)',
        url23:'',
        desc23:'',
        description:'',
        image:''

    },
    { 
        name:'Conditions in the Pacific Ocean',
        path:'conditions-pacific',
        url:'http://derecho.math.uwm.edu/models/quicklook-gtwo.png',
        des:'Currently Active Tropical Systems & Investigation Areas',
        url2:'https://www.cpc.ncep.noaa.gov/products/precip/CWlink/ghaz/gth_full.png',
        des2:'Global Tropics hazards Outlook',
        url3:'http://www.nhc.noaa.gov/xgtwo/two_pac_0d0.png',
        des3:'Active tropical systems and probability of cyclone formation during the next 48 hours in the Eastern Pacific',
        url4:'http://www.nhc.noaa.gov/xgtwo/two_pac_2d0.png',
        des4:'Two Day Graphical Weather Outlook / National Hurricane Center Miami, Florida',
        url5:'http://www.nhc.noaa.gov/xgtwo/two_pac_5d0.png',
        des5:'Active tropical systems and probability of cyclone formation during the next 5 days in the Eastern Pacific',
        url6:'http://images.intellicast.com/WxImages/CustomGraphic/tgepac1.gif',
        des6:'Current status of active tropical cyclones in the Pacific and possible trajectory and predicted intensity, with alerts, watches, warnings and potential for tropical storm and hurricane winds (official information from the latest bulletin)',
        url7:'http://tropic.ssec.wisc.edu/real-time/eastpac/images/xxirg9bbm.jpg',
        des7:'',
        url8:'http://sirocco.accuweather.com/sat_mosaic_640x480_public/ei/isaehpac.gif',
        des8:'East Pacific Satellite Animation',
        url9:'http://www.ssd.noaa.gov/PS/TROP/gglcontent/epac.gif',
        des9:'Pacific infrared satellite (animation)',
        url10:'http://www.ssd.noaa.gov/PS/TROP/TCFP/data/current/ep_cCUMP_048.gif',
        des10:'Probability of cyclone formation by weather during the next 48 hours',
        url11:'http://tropic.ssec.wisc.edu/real-time/mimic-tpw/epac/anim/latest72hrs.gif',
        des11:'Total precipitable water in the Eastern Pacific',
        url12:'http://tropic.ssec.wisc.edu/real-time/mtpw2/webAnims/tpw_nrl_colors/epac/mimictpw_epac_latest.gif',
        des12:'',
        url13:'http://www.ssd.noaa.gov/PS/TROP/DATA/RT/SST/PAC/20.jpg',
        des13:'Sea surface temperatures, NOAA analysis (SST/SST)',
        description:'',
        image:''
    },
    { 
        name:'Interactive forecast models',
        path:'interactive-forecast-models',
        url:'https://embed.windy.com/embed2.html?lat=25.245&lon=-83.584&zoom=4&level=surface&overlay=wind&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=true&detailLat=18.467&detailLon=-69.900&metricWind=km%2Fh&metricTemp=%C2%B0C',
        desc:'windy/windyty version for the Atlantic Ocean, the Pacific Ocean and the rest of the world.',
        description:'',
        image:''
    },
    { 
        name:'Conditions in Central America',
        path: 'conditions-central-america',
        url:'http://sirocco.accuweather.com/sat_mosaic_640x480_public/ei/isaecam.gif',
        desc:'Infrared satellite of Central America (animation)',
        url2:'http://sirocco.accuweather.com/sat_mosaic_640x480_public/IR/isacam.gif',
        desc2:'Satellite image of Mexico and Central America',
        url3:'',
        desc3:'',
        url4:'',
        desc4:'',
        url5:'',
        desc5:'',
        description:'',
        image:''
    },
    // { 
    //     name:'satellite images',
    //     url:'',
    //     desc:'',
    //     url2:'',
    //     desc2:'',
    //     url3:'',
    //     desc3:'',
    //     url4:'',
    //     desc4:'',
    //     url5:'',
    //     desc5:'',

    //     description:'',
    //     image:''
    // },
    { 
        name:'Conditions in the Caribbean Sea',
        path:'conditions-caribbean',
        url:'http://www.myfoxhurricane.com/custom/tropical/caribbean_mer_enh_ir_sat_1.jpg',
        desc:'satellite Image of the Caribbean Sea',
        url2:'http://sirocco.accuweather.com/sat_mosaic_640x480_public/EI/isaecar.gif',
        desc2:'satellite (Infrared) Image of the Caribbean Sea (animated)',
        url3:'http://sirocco.accuweather.com/sat_mosaic_640x480_public/IR/isacar.gif',
        desc3:'Satellite image of the Caribbean (animated)',
        url4:'http://sirocco.accuweather.com/sat_mosaic_640x480_public/ei/isaecatl.gif',
        desc4:'Infrared satellite of Venezuela, Colombia and the Caribbean (animation)',
        url5:'http://www.nhc.noaa.gov/tafb_latest/CAR_latest.gif',
        desc5:'Surface analysis of the Caribbean Sea',

        description:'',
        image:''
    },
    // { 
    //     name:'Conditions in Mexico',
    //     url:'',
    //     description:'',
    //     image:''
    // },
    { 
        name:'world maps',
        path:'world-maps',
        url:'http://www.ssd.noaa.gov/PS/TROP/TCFP/data/current/gl_rCUMP_048.gif',
        desc:'Probability of cyclone formation within 48 hours in the world',
        url2:'http://www.cpc.ncep.noaa.gov/products/analysis_monitoring/enso_update/gsstanim.gif',
        desc2:'Sea surface temperatures and anomalies (animation)',
        url3:'http://www.cpc.ncep.noaa.gov/products/analysis_monitoring/enso_update/gsstanim.gif',
        desc3:'Sea surface temperatures and anomalies (celsius) ',
        url4:'http://tropic.ssec.wisc.edu/real-time/mimic-tpw/global/anim/latest72hrs.gif',
        desc4:'Total precipitable water in the world',
        url5:'',
        desc5:'',


        description:'',
        image:''
    },
    { 
        name:'Satellite images for cyclone tracking',
        path:'satellite-images',
        url:'https://cdn.star.nesdis.noaa.gov/GOES16/ABI/GIFS/GOES16-TAW-02-900x540.gif',
        desc:'Satellite images of the Atlantic Ocean',
        url2:'https://cdn.star.nesdis.noaa.gov/GOES16/ABI/GIFS/GOES16-TAW-02-900x540.gif',
        desc2:'',
        url3:'https://cdn.star.nesdis.noaa.gov/GOES16/ABI/GIFS/GOES16-TAW-13-900x540.gif',
        desc3:'',
        url4:'https://cdn.star.nesdis.noaa.gov/GOES16/ABI/GIFS/GOES16-CAR-GEOCOLOR-1000x1000.gif',
        desc4:'',
        url5:'https://cdn.star.nesdis.noaa.gov/GOES16/ABI/GIFS/GOES16-CAR-13-1000x1000.gif',
        desc5:'',  
        description:'',
        image:''
    },
    { 
        name:'',
        path:'',
        url:'',
        description:'',
        image:''
    },
    
]